name: Shell Commands
on: [push]
jobs:
  run-shell-commands:
    runs-on: ubuntu:latest
    steps:
      - name: string
        run: echo "Welcome to SP SOFTWARE SOLUTIONS"
      - name: multiline script
        run: |
          node -v
          npm -v
